cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
    --time=36:00:00
default-resources:
  - partition=synergy,single,lattice,cpu2019,cpu2021
  - mem_mb=50000
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 150
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True

